# -*- coding: utf-8 -*-
"""MedicalinsuranceCostPredictionipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDpKhDWpgEGsYPeH7qCChP-2xgY0EDPA

1.

project 11:->Medical Insurance cost prediction

STEP 1. importing the dependencies
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
!pip3 install streamlit
import streamlit as st

import pickle
pickle_in=open('regressor.pkl','rb')
regressor=pickle.load(pickle_in)

"""STEP 2 Data collection and analysis"""

#loading the data from csv file to pandas dataframe
insurance_dataset =pd.read_csv('/content/archive.zip')

#print first 5 rows of the dataset
insurance_dataset.head()

#number of rows and columns
insurance_dataset.shape

#getting some information about the dataset
insurance_dataset.info()

"""CATEGORICAL FEATURES

 SEX

 SMOKER

 REGION

"""

# CHECKING FOR MISSING VALUES
insurance_dataset.isnull().sum()

"""0--> no missing values

DATA ANALYSIS
"""

#STATISTICAL MEASURES OF THE DATASET
insurance_dataset.describe()
# only for numerical values not categorical

#distribution of age value
sns.set()
plt.figure(figsize=(6,6))
sns.displot(insurance_dataset['age']) #distributed plot of age
plt.title('AGE DISTRIBUTION')
plt.show()

"""we use COUNT PLOT FOR CATEGORICAL features .

COUNT PLOT will give of values in male values ang no. of values in female .
"""

#gender column
plt.figure(figsize=(6,6))
sns.countplot(x='sex',data=insurance_dataset)
plt.title('sex distribution ')
plt.show()

insurance_dataset['sex'].value_counts()

#bmi distribution
plt.figure(figsize=(6,6))
sns.displot(insurance_dataset['bmi'])
plt.title('BMI DISTRIBUTION')
plt.show()

"""NORMAL BMI RANGE ->18.5 TO 24.9"""

#CHILDREN COLUMN
plt.figure(figsize=(6,6))
sns.countplot(x='children',data=insurance_dataset)
plt.title('CHILDREN DATASET')
plt.show()

insurance_dataset['children'].value_counts()

#smoker column
 plt.figure(figsize=(6,6))
 sns.countplot(x='smoker',data=insurance_dataset)
 plt.title('SMOKER DISTRIBUTION')
 plt.show()

insurance_dataset['smoker'].value_counts()

#region column
plt.figure(figsize=(6,6))
sns.countplot(x='region',data=insurance_dataset)
plt.title('REGION DISTRIBUTION ')
plt.show()

insurance_dataset['region'].value_counts()

#distribution of charges
plt.figure(figsize=(6,6))
sns.displot(insurance_dataset['charges'])
plt.title('CHARGES DISTRIBUTION')
plt.show()

"""STEP3 Data Preprocessing

encoding the categorical values

into numerical values
(because computer cannot read alphabets so we need to convert it into 0 and 1)
"""

#encoding sex column
insurance_dataset.replace({'sex':{'male':0,'female':1}},inplace=True)

#encoding smoker column
insurance_dataset.replace({'smoker':{'yes':0,'no':1}},inplace=True)

#encoding region column
insurance_dataset.replace({'region':{'southeast':0,'southwest':1,'northeast':2,'northwest':3}},inplace=True)

insurance_dataset

"""now all the categorical values are converted to numerical values

STEP -4

SPLITTING THE FEATURES AND TARGETS

1= col

0= row
"""

X=insurance_dataset.drop(columns='charges' ,axis=1) #we want to remove target(charges ) col from x axis
Y=insurance_dataset['charges']

print(X)

print(Y)

"""splitting the data into train and test data"""

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

print(X.shape,X_train.shape,X_test.shape)

print(Y.shape,Y_train.shape,Y_test.shape)

"""MODEL TRAINING

LINEAR REGRESSION
"""

#LOADING THE LINEAR REGRESSION MODEL
regressor=LinearRegression()

regressor.fit(X_train,Y_train)

import pickle
filename = 'regressor.pkl'
pickle.dump(regressor, open(filename, 'wb'))

import pickle

# Save the trained model
with open('regressor.pkl', 'wb') as f:
    pickle.dump(regressor, f)

from google.colab import files
files.download('regressor.pkl')

"""MODEL EVALUATION"""

#PREDICTION ON TRAINING DATA
training_data_prediction=regressor.predict(X_train)

#performance metrics= R square value [0,1]
r2_train=metrics.r2_score(Y_train,training_data_prediction)
print('R square value: ' ,r2_train)

#predicton on test data
test_data_prediction=regressor.predict(X_test)

#R square value

r2_test=metrics.r2_score(Y_test,test_data_prediction)
print('R square value:',r2_test)

"""good fit= training data value = test data value

BUILDING A PREDICTIVE VALUE
"""

input_data=(31,1,25.74,0,1,0)
#changing the input_data(tuple) to a numpy array
input_data_as_numpy_array=np.asarray(input_data)

#reshape the array (because we want array for only 1 data point now not all )
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)

prediction=regressor.predict(input_data_reshaped)
print(prediction)
print('The prediction cost is USD',prediction[0])